name: pynq
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - matplotlib
    - numpy
    - pandas
    - tensorflow
    - pynq==2.5.2
    - git+git://github.com/google/qkeras.git#egg=qkeras
    - git+git://github.com/jmduarte/hls4ml.git@pynq#egg=hls4ml[profiling]

